<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-11-09 00:15
=======
# Generated by Django 5.1.3 on 2024-11-30 19:50
>>>>>>> 0e8ab1a (Add CORS headers.)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organizer_id', models.IntegerField()),
                ('participant_ids', models.JSONField(blank=True, default=list)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduling.event')),
            ],
        ),
    ]
