# Generated by Django 5.1.1 on 2024-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=255)),
                ('EventDesc', models.TextField()),
                ('EventDate', models.DateTimeField()),
                ('EventLocation', models.CharField(max_length=255)),
            ],
        ),
    ]
